sudo: required

before_install:
  - sudo add-apt-repository ppa:kelleyk/emacs -y
  - sudo apt-get update -q
  - sudo apt-get install emacs25 -y

script:
  - EMACS=emacs-25.3 ./test.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: never
