dist: xenial

addons:
  apt:
    sources:
      - sourceline: "ppa:kelleyk/emacs"
    packages:
      - emacs25

script:
  - EMACS=emacs-25.3 ./test.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always
