name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Emacs
        uses: purcell/setup-emacs@bdc64dc730ae1fcba200bfd52cb1b4cf6159cbe5 # master
        with:
          version: "31.1"
      - name: Install aspell
        run: sudo apt-get install aspell
      - name: Run test
        run: ./test.sh
